In [298]:
import numpy as np

In [299]:
with open('puzzle_input.txt') as f:
    rows = [line.rstrip() for line in f.readlines()]

In [300]:
rows

['@@@..@@....@.@.@@.@.....@@@@@@..@.@@@@@@@@@.@@@@@@..@@@@@.@@.@@.@.@.@..@@@@.@.@.@.@@..@....@.@@@...@@.@@@@...@@@@@@..@@@@@@..@@@@@@.@@..@.@',
 '@@@@.@@@..@@@.@.@.@@@@..@.@@..@.@@@.@.@...@.@@@@@@@@@@@.@@@.@@@@@.@@.@@@@@.@.@@@.@.@.@@@@@@..@.@..@@.@.@@@.@.@.@@.@@.@@.@@.@@@@.@@@.@@@.@@@',
 '@@@@.@.@@@@.@@.@@@.@.@@@@@.@..@@@.@@..@@@.@@@..@@.@@...@.@@.@@@.@@@.@.@@.@@@@@@.@@.@@.@@.@@.@@@.@@@@@@@@@@@@@@@@@.@@.@.@@@@@@@@...@@@@@.@@@',
 '.@@@.@@@@.@@@@@@@..@@..@@.@@@@@@.@@.@@@@@@@.@@@@@@.@.@..@@.@@@..@@.@@@@.@@@@@.@@.@@.@@.@@@@@@@@@@.@@.@@@.@.@@.@@@@.@@@.@.@@@@@@@....@@.@.@@',
 '...@.@.@@...@@@@@@@@@.@@.@..@..@@..@@@..@@...@@@@@@@@.@@@.@@....@@@@@@@@@.@@@@@@@@@.@@@@.@.@@@.@@.@@@@@.@@..@@@@..@@@@...@@.@@@..@@@..@@.@@',
 '@@...@@.@@@@.@..@@@@.@@@@@.@@...@..@..@@.@..@@@.@@@@@@@@@@..@@@..@@@@..@@@@@@@@.@@@.@@@@.@@@..@@.@@.@@@@@...@@@@@@@..@@@.@@@@@..@@.@@..@@..',
 '.@..@@@@@@...@.@@@.@.@@.@.@.@@@@@.@.@@@@@@@@@@@@..@@@@@@@@@.@@.@..@.@@..@@@@..@.@@..@.@@.@@@@..@@@@@.@...@.@@.@@.@@@@@.@..@.@@@@@@.@.@

In [301]:
window_size = 3
padding = int((window_size-1)/2)

rows_array = np.zeros((len(rows),len(rows[0])))
rows_array_padded = np.zeros((len(rows)+2*int(np.floor((window_size-1)/2)),len(rows[0])+2*int(np.floor((window_size-1)/2))))
for row_idx,row in enumerate(rows):
    for roll_idx,roll in enumerate(row):
        if roll == '.':
            roll = 0
        else:
            roll =1
        rows_array[row_idx,roll_idx] =roll
        rows_array_padded[row_idx+int(np.floor((window_size-1)/2)),roll_idx+int(np.floor((window_size-1)/2))]= roll

rows_array_markers = np.zeros_like(rows_array,dtype='U1')

for row_idx,row in enumerate(rows_array):
    for roll_idx, roll in enumerate(row):
        if roll == 1:
            rows_array_markers[row_idx,roll_idx]='@'
        else:
            rows_array_markers[row_idx,roll_idx]='.'


print(rows_array)

[[1. 1. 1. ... 1. 0. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 0. 1. 1.]
 [1. 1. 0. ... 1. 1. 1.]
 [1. 0. 0. ... 1. 1. 1.]]


In [302]:
markers = rows_array_markers.copy()
count=0
for row_idx, row in enumerate(rows_array):
    # print(row)
    for roll_idx, roll in enumerate(row):
        window = rows_array_padded[row_idx:row_idx+2*(padding)+1,roll_idx:roll_idx+2*(padding)+1]
        centre_idx = (int((len(window)-1)/2),int((len(window[0])-1)/2))
        before = window[centre_idx]
        window[centre_idx]=0
        window_sum = np.sum(window)
        window[centre_idx]=before
        if window[centre_idx] == 1 and window_sum < 4:
            count+=1
            markers[row_idx,roll_idx]='x'
        window[centre_idx]=before
print(count)

1474


In [303]:
print(markers)

[['x' '@' '@' ... 'x' '.' 'x']
 ['@' '@' '@' ... '@' '@' '@']
 ['@' '@' '@' ... '@' '@' '@']
 ...
 ['x' '@' '@' ... '.' '@' '@']
 ['@' '@' '.' ... '@' '@' '@']
 ['x' '.' '.' ... 'x' '@' 'x']]
